name: Validate Schemas

on:
  pull_request:
    branches:
      - stable
      - unstable
      - develop/gateway
      - develop/portal

jobs:
  kubeval-chart:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s:
          - v1.19.0
          - v1.19.16
          - v1.20.0
          - v1.20.15
          - v1.21.0
          - v1.21.14
          - v1.22.0
          - v1.22.17
          - v1.23.0
          - v1.23.17
          - v1.24.0
          - v1.24.12
          - v1.25.0
          - v1.25.8
          - v1.26.0
          - v1.26.3
    steps:
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh
